---
- name: Create database
  mysql_db:
    name: "{{ nextcloud_db_name }}"
    login_host: "{{ nextcloud_db_host }}"
    login_user: "{{ nextcloud_db_admin_user }}"
    login_password: "{{ nextcloud_db_admin_password }}"
    config_file: /dev/null
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Create database user
  mysql_user:
    login_host: "{{ nextcloud_db_host }}"
    login_user: "{{ nextcloud_db_admin_user }}"
    login_password: "{{ nextcloud_db_admin_password }}"
    name: "{{ nextcloud_db_user }}"
    password: "{{ nextcloud_db_password }}"
    host: "{{ nextcloud_db_user_host }}"
    priv: "{{ nextcloud_db_name }}.*:{{ nextcloud_db_user_privileges }}"
    state: present
