---
- name: Pull the Docker image from the Registry
  docker_image:
    name: "{{ nextcloud_image_name }}"
    tag: "{{ nextcloud_image_tag }}"
    source: pull
    force_source: yes
  when: nextcloud_image_update == true

- name: Check if the container already exists
  docker_container_info:
    name: "{{ nextcloud_container_name }}"
  register: container_status

- name: Ensure the container is stopped if exists
  docker_container:
    name: "{{ nextcloud_container_name }}"
    state: stopped
  when: container_status.exists

- name: Create a volume for the Docker container
  docker_volume:
    volume_name: "{{ item }}"
    state: present
  with_items:
    - "{{ nextcloud_main_volume_name }}"
    - "{{ nextcloud_apps_volume_name }}"
    - "{{ nextcloud_config_volume_name }}"
    - "{{ nextcloud_data_volume_name }}"
  notify: Restart Nextcloud

- name: Create a container for Nextcloud
  docker_container:
    name: "{{ nextcloud_container_name }}"
    image: "{{ nextcloud_image_name }}"
    recreate: yes
    state: present
    published_ports:
      - "{{ nextcloud_host_port | default(8080) }}:8080"
    volumes: "{{ nextcloud_container_volumes }}"
    restart_policy: "{{ nextcloud_restart_policy }}"
    env: "{{ nextcloud_envs }}"
  notify: Restart Nextcloud
  register: container_result
